default : &DEFAULT

  # General
  verbose: True 
  device: 'cuda:1' 
  seed: 42
  min_epoch: 0
  wb: False
  rmse: 1
  per: False
  

  # Model
  afno2d:
    hidden_size: 768 #768 #768
    sparsity_threshold: 0.01
    num_blocks: 8
    hard_thresholding_fraction: 1
    hidden_size_factor: 1 
    double_skip: True
    drop_path: 0
    mlp_ratio: 4
    n_blocks: 3
    attn_heads: 8

  mlp:
    in_features: 768 #768 #768
    hidden_features: 3072 #1536 #3072 #1536 #3072 #3072 #1536
    out_features: 768 #768 #768
    drop: 0.1
    
  # Optimizer
  opt:
    epochs: 100
    lr: 1e-3
    weight_decay: 1e-5
    scheduler: 'ReduceLROnPlateau' #'StepLR' # Or 'CosineAnnealingLR' OR 
    step_size: 15
    gamma: 0.1
    

  # Dataset related
  data:
    data_dir: "data/"
    file_prefix: ocean 
    file_prefix_atm: atm
    variable: ['thetao','so','uo','vo','zos'] # thetao #
    atm_variable: ['ssr','tp','u10','v10','msl','tcc']
    out_variable: ['thetao','so','uo','vo','zos']
    img_size: [224,224]
    patch_size: [8,8]
    in_chs: 11
    atm_chs: 6
    out_chs: 5
    emd_dim: 768 #384 #384
    drop_rate: 0
    pos_drop_rate: 0
    drop_path_rate: 0
    dynamic_size: True
    batch_size: 32 #64 #128
    shuffle: False

  plot:
    input_day: 10021
    num_days: 9 #5
    

  